=== maria85290/DAW2020/T2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (cabeçalho, equipa, resumo, entregaveis )>

<!ELEMENT cabeçalho (nomeChave, titulo, subtitulo, dataInicio, dataFim, supervisor)>
<!ELEMENT nomeChave (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT dataInicio (#PCDATA)>
<!ELEMENT dataFim (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor href CDATA #REQUIRED>


<!ELEMENT equipa (pessoa)+>
<!ELEMENT pessoa (nome,numero,email,linkWeb)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ATTLIST numero id ID #REQUIRED >
<!ELEMENT email (#PCDATA)>
<!ELEMENT linkWeb (#PCDATA)>
<!ATTLIST linkWeb href CDATA #IMPLIED>

<!ELEMENT resumo (paragrafo)+>
<!ELEMENT paragrafo (#PCDATA|italico|negrito|sublinhado|linkExt|linkInt)* >
<!ELEMENT italico (#PCDATA | linkExt | linkInt)* >
<!ELEMENT negrito (#PCDATA| linkExt| linkInt)*>
<!ELEMENT sublinhado (#PCDATA|linkExt|linkInt)*>
<!ELEMENT linkExt (#PCDATA)>
<!ELEMENT linkInt (#PCDATA)>
<!ATTLIST linkExt href CDATA #REQUIRED>
<!ATTLIST linkInt href CDATA #REQUIRED>

<!ELEMENT entregaveis (entregavel)+>
<!ELEMENT entregavel (#PCDATA)>
<!ATTLIST entregavel href CDATA #IMPLIED >

=== maria85290/DAW2020/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pr.css"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
 <cabeçalho>
     <nomeChave>DAW2020::TP2</nomeChave>
     <titulo>Criar o DTD para o Project Record </titulo>
     <subtitulo>Trabalho de casa 2</subtitulo>
     <dataInicio> 21.10.2020 </dataInicio>
     <dataFim> 28.10.2020 </dataFim>
     <supervisor href= "http://www4.di.uminho.pt/~jcr/"> José Carlos Ramalho </supervisor>
 </cabeçalho>  
 <equipa>
     <pessoa>
         <nome>Maria Laura de Araújo Barbosa</nome>
         <numero id = "pg42844"></numero>  
         <email>pg42844@alunos.uminho.pt</email>
         <linkWeb href = "https://github.com/maria85290/DAW2020"> GitHub </linkWeb>
     </pessoa>
 </equipa>
 <resumo>
     <paragrafo>
         <texto>O objetivo deste segundo projeto é criar um DTD (Document Type Definition) para o Project Record. 
             Este documento foi criado com o auxilio da ferramenta OxygenXML editor.</texto>
     </paragrafo>
     <paragrafo>
        <texto> Além disso, pretende-se criar o Projet Record do trabalho desenvolvido. </texto>
     </paragrafo>
 </resumo>
 <entregaveis>
     <entregavel href= "https://github.com/maria85290/DAW2020/blob/main/T2/pr.dtd"> DTD do Project Record </entregavel>
     <entregavel> Project Record do trabalho desenvolvido </entregavel>
 </entregaveis>
</pr>

=== maria85290/DAW2020/T3/project__record.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="pr.css"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <cabeçalho>
        <nomeChave>DAW2020::TP3</nomeChave>
        <titulo>DTD e uma stylesheet XSLT o dataset dos arqueossítios do NW português. </titulo>
        <subtitulo>Trabalho de casa 3</subtitulo>
        <dataInicio> 28.10.2020 </dataInicio>
        <dataFim> 4.11.2020 </dataFim>
        <supervisor href= "http://www4.di.uminho.pt/~jcr/"> José Carlos Ramalho </supervisor>
    </cabeçalho>  
    <equipa>
        <pessoa>
            <nome>Maria Laura de Araújo Barbosa</nome>
            <numero id = "pg42844"></numero>  
            <email>pg42844@alunos.uminho.pt</email>
            <linkWeb href = "https://github.com/maria85290/DAW2020"> GitHub </linkWeb>
        </pessoa>
    </equipa>
    <resumo>
        <paragrafo>
            Ojetivo deste trabalho é criar um DTD e uma stylesheet XSLT que gere um website para o dataset dos arqueossítios do NW português.
        </paragrafo>
            
        <paragrafo>
            O DTD foi criado com o auxilio da ferramenta <italico>OxygenXML editor.</italico> Começou-se por definir a raiz:
            <negrito>ARQSITS</negrito> e a partir daí definiu-se os restantes elementos recursivamente. 
            Em relação ao WebSite, estabeleceu-se que a página principal seria o indice (ordenado por ordem alfabetica)
            que permite navegar até cada um dos arqueossítios presentes no datasets. 
        </paragrafo>
    </resumo>
    <entregaveis>
        <entregavel href= "https://github.com/maria85290/DAW2020/blob/main/T3/arq.dtd"> DTD do Project Record </entregavel>
        <entregavel href= "https://github.com/maria85290/DAW2020/blob/main/T3/arq-site.xsl"> Stylesheet XSLT que gera o Website </entregavel>
    </entregaveis>
</pr>
